services:  
  vllm-openai:
    image: vllm/vllm-openai:v0.9.1
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    ports:
      - "8000:8000"
    ipc: host
    command: >
      --model deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
      --tensor-parallel-size 2
      --gpu_memory_utilization 0.95
      --max_model_len 50000

  