[project]
name = "vllm-startup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "setuptools>=80.0.1",
    "vllm>=0.8.5",
]
